version: "3.9"
services:
  server:
    build: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/app
    environment:
      FLASK_ENV: development
    networks:
      - my-network
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    networks:
      - my-network
    depends_on:
      - server

networks:
  my-network:
